# Generated by Django 3.2.13 on 2023-12-08 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('q_food', '0002_auto_20231128_0215'),
        ('GPT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='q_food.question')),
            ],
        ),
        migrations.DeleteModel(
            name='GPTAnswer',
        ),
    ]
