# Generated by Django 3.2.13 on 2023-12-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q_food', '0002_auto_20231128_0215'),
        ('GPT', '0002_auto_20231209_0113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Infor',
            new_name='INFORMATION',
        ),
    ]
