# Generated by Django 3.2.13 on 2023-12-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_food', '0002_auto_20231128_0215'),
        ('GPT', '0003_rename_infor_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='INFORMATION_Q',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='INFORMATION',
            new_name='INFORMATION_A',
        ),
    ]
